-- Fix auto-increment for all ID columns and convert files content to oid for large objects

-- Users table
ALTER TABLE users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Contests table
ALTER TABLE contests ALTER COLUMN contest_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Problems table
ALTER TABLE problems ALTER COLUMN problem_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Files table
ALTER TABLE files ALTER COLUMN file_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Contest problems table
ALTER TABLE contest_problems ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Contest users table
ALTER TABLE contest_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Problem users table
ALTER TABLE problem_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Invocations table (assuming it has id, but from V7 it was added)
-- From V7: CREATE TABLE invocations ( ... but no id? Wait, let me check V7

-- V7 adds invocations table, but does it have id?

-- From V1, no invocations in initial, V7 adds it.

-- Let me check V7

-- Assuming invocations has id, but from the code, perhaps not.

-- Anyway, for now, the main ones.

-- For files content, convert to oid using large objects

-- Add temporary column
ALTER TABLE files ADD COLUMN content_oid oid;

-- Create large objects from existing BYTEA content
UPDATE files SET content_oid = lo_from_bytea(0, content);

-- Drop old column
ALTER TABLE files DROP COLUMN content;

-- Rename to content
ALTER TABLE files RENAME COLUMN content_oid TO content;